require:
  - "./maintainers/rubocop/coverage_suppression.rb"
  - "./maintainers/rubocop/type_suppression.rb"

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  UseProjectIndex: true
  inherit_mode:
    merge:
      - Include
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Include:
    - ".simplecov"
    - ".github/scripts/**/*.rb"
  Exclude:
    - "lib/volcano/generated/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/CyclomaticComplexity:
  Max: 5

Performance/ChainArrayAllocation:
  Enabled: true

Performance/SelectMap:
  Enabled: true

RSpec/ExampleLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/MultipleExpectations:
  Max: 5

Style/Documentation:
  Enabled: true
  Exclude:
    - "spec/**/*"

Volcano/CoverageSuppression:
  Enabled: true

Volcano/TypeSuppression:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true
  AllowedCops:
    - Metrics/ParameterLists
    - Lint/UnderscorePrefixedVariableName
    - Lint/NameTypo
    - Lint/UnusedPrivateMethod
    - Lint/NumberConversion

Lint/ConstantResolution:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/NumberConversion:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnusedPrivateMethod:
  Enabled: true

RSpec/SpecFilePathFormat:
  CustomTransform:
    SpecSupport: ""
