module Volcano
  class Auth
    def current_session: () -> Session?
    def current_session=: (Session session) -> void
    def on_auth_state_change: () ?{ (Symbol, Session?) -> void } -> AuthSubscription
    def sign_in: (email: String, password: String) -> Session
    def sign_up: (email: String, password: String, ?metadata: session_user_input, ?sign_in_when_allowed: bool) -> SignUpResult
    def sign_in_anonymously: (?metadata: session_user_input) -> Session
    def convert_anonymous: (email: String, password: String, ?metadata: session_user_input) -> User
    def confirm_email: (token: String) -> nil
    def resend_confirmation: (email: String) -> nil
    def reset_password_for_email: (email: String) -> nil
    def reset_password: (token: String, new_password: String) -> nil
  end
end
