module Volcano
  class Locks
    def get: (String key, ?request_id: String?) -> LockState
    def acquire: (String key, ttl: Integer, ?token: String?, ?request_id: String?) -> LockLease
    def renew: (String key, LockLease lease, ttl: Integer, ?request_id: String?) -> LockLease
    def release: (String key, LockLease lease, ?request_id: String?) -> nil
    def force_release: (String key, ?request_id: String?) -> nil
    def with_lock: [T] (String key, ttl: Integer, ?token: String?, ?request_id: String?) { (LockGuard) -> T } -> T
  end
end
