name: Lint docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/lint-docs.yml'

permissions:
  contents: read

jobs:
  docs:
    uses: Kong/volcano-docs/.github/workflows/lint-docs.yml@2eed9e93cae0b070f57788e7c270ccfbb4cd4579
    with:
      path: docs
